/*
 * This file is generated by jOOQ.
 */
package org.vtb.jooq;


import org.vtb.jooq.tables.Atm;
import org.vtb.jooq.tables.AtmService;
import org.vtb.jooq.tables.FlywaySchemaHistory;
import org.vtb.jooq.tables.Office;
import org.vtb.jooq.tables.Registration;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.atm</code>.
     */
    public static final Atm ATM = Atm.ATM;

    /**
     * The table <code>public.atm_service</code>.
     */
    public static final AtmService ATM_SERVICE = AtmService.ATM_SERVICE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.office</code>.
     */
    public static final Office OFFICE = Office.OFFICE;

    /**
     * The table <code>public.registration</code>.
     */
    public static final Registration REGISTRATION = Registration.REGISTRATION;
}
