/*
 * This file is generated by jOOQ.
 */
package org.vtb.jooq.tables;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.vtb.jooq.Keys;
import org.vtb.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Atm extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.atm</code>
     */
    public static final Atm ATM = new Atm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.atm.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.atm.address</code>.
     */
    public final TableField<Record, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.atm.latitude</code>.
     */
    public final TableField<Record, BigDecimal> LATITUDE = createField(DSL.name("latitude"), SQLDataType.NUMERIC(8, 6).nullable(false), this, "");

    /**
     * The column <code>public.atm.longitude</code>.
     */
    public final TableField<Record, BigDecimal> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.NUMERIC(8, 6).nullable(false), this, "");

    /**
     * The column <code>public.atm.all_day</code>.
     */
    public final TableField<Record, Boolean> ALL_DAY = createField(DSL.name("all_day"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private Atm(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Atm(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.atm</code> table reference
     */
    public Atm(String alias) {
        this(DSL.name(alias), ATM);
    }

    /**
     * Create an aliased <code>public.atm</code> table reference
     */
    public Atm(Name alias) {
        this(alias, ATM);
    }

    /**
     * Create a <code>public.atm</code> table reference
     */
    public Atm() {
        this(DSL.name("atm"), null);
    }

    public <O extends Record> Atm(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, ATM);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.ATM_PKEY;
    }

    @Override
    public Atm as(String alias) {
        return new Atm(DSL.name(alias), this);
    }

    @Override
    public Atm as(Name alias) {
        return new Atm(alias, this);
    }

    @Override
    public Atm as(Table<?> alias) {
        return new Atm(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Atm rename(String name) {
        return new Atm(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Atm rename(Name name) {
        return new Atm(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Atm rename(Table<?> name) {
        return new Atm(name.getQualifiedName(), null);
    }
}
