/*
 * This file is generated by jOOQ.
 */
package org.vtb.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.vtb.jooq.Keys;
import org.vtb.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtmService extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.atm_service</code>
     */
    public static final AtmService ATM_SERVICE = new AtmService();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.atm_service.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.atm_service.atm_id</code>.
     */
    public final TableField<Record, Long> ATM_ID = createField(DSL.name("atm_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.atm_service.data</code>.
     */
    public final TableField<Record, JSONB> DATA = createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "");

    private AtmService(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private AtmService(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.atm_service</code> table reference
     */
    public AtmService(String alias) {
        this(DSL.name(alias), ATM_SERVICE);
    }

    /**
     * Create an aliased <code>public.atm_service</code> table reference
     */
    public AtmService(Name alias) {
        this(alias, ATM_SERVICE);
    }

    /**
     * Create a <code>public.atm_service</code> table reference
     */
    public AtmService() {
        this(DSL.name("atm_service"), null);
    }

    public <O extends Record> AtmService(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, ATM_SERVICE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.ATM_SERVICE_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.ATM_SERVICE_ATM_ID_KEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.ATM_SERVICE__ATM_SERVICE_ATM_ID_FKEY);
    }

    private transient Atm _atm;

    /**
     * Get the implicit join path to the <code>public.atm</code> table.
     */
    public Atm atm() {
        if (_atm == null)
            _atm = new Atm(this, Keys.ATM_SERVICE__ATM_SERVICE_ATM_ID_FKEY);

        return _atm;
    }

    @Override
    public AtmService as(String alias) {
        return new AtmService(DSL.name(alias), this);
    }

    @Override
    public AtmService as(Name alias) {
        return new AtmService(alias, this);
    }

    @Override
    public AtmService as(Table<?> alias) {
        return new AtmService(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtmService rename(String name) {
        return new AtmService(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtmService rename(Name name) {
        return new AtmService(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtmService rename(Table<?> name) {
        return new AtmService(name.getQualifiedName(), null);
    }
}
