/*
 * This file is generated by jOOQ.
 */
package org.vtb.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.vtb.jooq.tables.Atm;
import org.vtb.jooq.tables.AtmService;
import org.vtb.jooq.tables.FlywaySchemaHistory;
import org.vtb.jooq.tables.Office;
import org.vtb.jooq.tables.Registration;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.atm</code>.
     */
    public final Atm ATM = Atm.ATM;

    /**
     * The table <code>public.atm_service</code>.
     */
    public final AtmService ATM_SERVICE = AtmService.ATM_SERVICE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.office</code>.
     */
    public final Office OFFICE = Office.OFFICE;

    /**
     * The table <code>public.registration</code>.
     */
    public final Registration REGISTRATION = Registration.REGISTRATION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Atm.ATM,
            AtmService.ATM_SERVICE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Office.OFFICE,
            Registration.REGISTRATION
        );
    }
}
